export interface TFields {
  name: string;
  display: boolean;
  filtered: boolean;
}

export enum fieldNames {
  cotacao = "Cotação",
  bgraham = "B. Graham",
  bazin = "Bazin",
  cagr = "CAGR",
  dy = "DY",
  growth = "Growth",
  have = "Have Date",
  lpa = "LPA",
  dlebitida = "D/ebitida",
  margemliquida = "Margem Liquida",
  payout = "Payout",
  pl = "PL",
  plmedio = "PL Médio",
  pvp = "PVP",
  sector = "Setor",
  tagalong = "Tag Along",
  vpa = "VPA",
  pl1 = "PL 1",
  pl2 = "PL 2",
  pl3 = "PL 3",
  pl4 = "PL 4",
  roe = "ROE",
  sinalaluguel = "Sinal Aluguel",
  magicformula = "M. Formula",
  insider = "Insider",
  liquidez = "Liquidez",
  onlyB3 = "Only B3",
  onlyBDR = "Only BDR",
}

export const fields = [
  { name: fieldNames.cotacao, display: true, filtered: false, isColumn: true },
  { name: fieldNames.bgraham, display: true, filtered: false, isColumn: true },
  { name: fieldNames.bazin, display: true, filtered: false, isColumn: true },
  //{ name: 'MSeg. Graham', display: true , filtered: false, isColumn: true},
  { name: fieldNames.cagr, display: false, filtered: false, isColumn: true },
  { name: fieldNames.dy, display: true, filtered: false, isColumn: true },
  { name: fieldNames.growth, display: false, filtered: false, isColumn: true },
  { name: fieldNames.have, display: false, filtered: false, isColumn: true },
  { name: fieldNames.lpa, display: false, filtered: false, isColumn: true },
  {
    name: fieldNames.dlebitida,
    display: true,
    filtered: false,
    isColumn: true,
  },
  {
    name: fieldNames.margemliquida,
    display: true,
    filtered: false,
    isColumn: true,
  },
  { name: fieldNames.payout, display: true, filtered: false, isColumn: true },
  { name: fieldNames.pl, display: true, filtered: false, isColumn: true },
  { name: fieldNames.plmedio, display: true, filtered: false, isColumn: true },
  { name: fieldNames.pvp, display: true, filtered: false, isColumn: true },
  { name: fieldNames.sector, display: false, filtered: false, isColumn: true },
  {
    name: fieldNames.tagalong,
    display: false,
    filtered: false,
    isColumn: true,
  },
  { name: fieldNames.vpa, display: true, filtered: false, isColumn: true },
  { name: fieldNames.pl1, display: false, filtered: false, isColumn: true },
  { name: fieldNames.pl2, display: false, filtered: false, isColumn: true },
  { name: fieldNames.pl3, display: false, filtered: false, isColumn: true },
  { name: fieldNames.pl4, display: false, filtered: false, isColumn: true },
  { name: fieldNames.roe, display: true, filtered: false, isColumn: true },
  {
    name: fieldNames.sinalaluguel,
    display: true,
    filtered: false,
    isColumn: true,
  },
  {
    name: fieldNames.magicformula,
    display: true,
    filtered: false,
    isColumn: true,
  },
  { name: fieldNames.insider, display: true, filtered: false, isColumn: true },
  { name: fieldNames.liquidez, display: true, filtered: false, isColumn: true },
  { name: fieldNames.onlyB3, display: false, filtered: false, isColumn: false },
  {
    name: fieldNames.onlyBDR,
    display: false,
    filtered: false,
    isColumn: false,
  },
];
