export interface TFields {
  name: string;
  display: boolean;
  filtered: boolean;
}

export enum fieldNames {
  cotacao = 'Cotação',
  bgraham = 'B. Graham',
  bazin = 'Bazin',
  cagr = 'CAGR',
  dy = 'DY',
  growth = 'Growth',
  have = 'Have Date',
  lpa = 'LPA',
  dlebitida = 'D/ebitida',
  margemliquida = 'Margem Liquida',
  payout = 'Payout',
  pl = 'PL',
  plmedio = 'PL Médio',
  pvp = 'PVP',
  sector = 'Setor',
  tagalong = 'Tag Along',
  vpa = 'VPA',
  pl1 = 'PL 1',
  pl2 = 'PL 2',
  pl3 = 'PL 3',
  pl4 = 'PL 4',
  roe = 'ROE',
  sinalaluguel = 'Sinal Aluguel',
  magicformula = 'M. Formula',
  insider = 'Insider',
  liquidez = 'Liquidez',
}

export const fields = [
  { name: fieldNames.cotacao, display: true, filtered: false },
  { name: fieldNames.bgraham, display: true, filtered: false },
  { name: fieldNames.bazin, display: true, filtered: false },
  //{ name: 'MSeg. Graham', display: true , filtered: false},
  { name: fieldNames.cagr, display: false, filtered: false },
  { name: fieldNames.dy, display: true, filtered: false },
  { name: fieldNames.growth, display: false, filtered: false },
  { name: fieldNames.have, display: false, filtered: false },
  { name: fieldNames.lpa, display: false, filtered: false },
  { name: fieldNames.dlebitida, display: true, filtered: false },
  { name: fieldNames.margemliquida, display: true, filtered: false },
  { name: fieldNames.payout, display: true, filtered: false },
  { name: fieldNames.pl, display: true, filtered: false },
  { name: fieldNames.plmedio, display: true, filtered: false },
  { name: fieldNames.pvp, display: true, filtered: false },
  { name: fieldNames.sector, display: false, filtered: false },
  { name: fieldNames.tagalong, display: false, filtered: false },
  { name: fieldNames.vpa, display: true, filtered: false },
  { name: fieldNames.pl1, display: false, filtered: false },
  { name: fieldNames.pl2, display: false, filtered: false },
  { name: fieldNames.pl3, display: false, filtered: false },
  { name: fieldNames.pl4, display: false, filtered: false },
  { name: fieldNames.roe, display: true, filtered: false },
  { name: fieldNames.sinalaluguel, display: true, filtered: false },
  { name: fieldNames.magicformula, display: true, filtered: false },
  { name: fieldNames.insider, display: true, filtered: false },
  { name: fieldNames.liquidez, display: true, filtered: false },
];
